runtime: nodejs18
env: standard
instance_class: F1  # Choose instance size (F1 is small & free-tier eligible)
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
env_variables:
  MONGODB_URI: "mongodb+srv://root:pQ5s5EuBekHAVof2@coderhouse.z4kpz.mongodb.net/?retryWrites=true&w=majority&appName=CoderHouse"
  JWT_SECRET: "my_jwt_secret"  
